version: "3.9"

services:
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    container_name: crypto-miner-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crypto-miner-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
    command: npm run dev

  db:
    image: postgres:15
    container_name: crypto-miner-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: cryptominer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: crypto-miner-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
